const users = [
    {
      sno: 1,
      name: "John Doe",
      email: "john.doe@example.com",
      role: "Admin",
      department: "IT",
    },
    {
      sno: 2,
      name: "Jane Smith",
      email: "jane.smith@example.com",
      role: "User",
      department: "Marketing",
    },
    {
      sno: 3,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      role: "Editor",
      department: "Content",
    },
    {
      sno: 4,
      name: "Bob Brown",
      email: "bob.brown@example.com",
      role: "Moderator",
      department: "Support",
    },
    {
      sno: 5,
      name: "Charlie Davis",
      email: "charlie.davis@example.com",
      role: "User",
      department: "Sales",
    },
    {
      sno: 6,
      name: "David Wilson",
      email: "david.wilson@example.com",
      role: "Admin",
      department: "IT",
    },
    {
      sno: 7,
      name: "Emma Thompson",
      email: "emma.thompson@example.com",
      role: "Editor",
      department: "Content",
    },
    {
      sno: 8,
      name: "Frank White",
      email: "frank.white@example.com",
      role: "User",
      department: "Marketing",
    },
    {
      sno: 9,
      name: "Grace Lee",
      email: "grace.lee@example.com",
      role: "Moderator",
      department: "Support",
    },
    {
      sno: 10,
      name: "Henry Clark",
      email: "henry.clark@example.com",
      role: "User",
      department: "HR",
    },
    {
      sno: 11,
      name: "Ivy Harris",
      email: "ivy.harris@example.com",
      role: "Admin",
      department: "IT",
    },
    {
      sno: 12,
      name: "Jack Martin",
      email: "jack.martin@example.com",
      role: "Editor",
      department: "Content",
    },
    {
      sno: 13,
      name: "Kate Lewis",
      email: "kate.lewis@example.com",
      role: "User",
      department: "Finance",
    },
    {
      sno: 14,
      name: "Liam Walker",
      email: "liam.walker@example.com",
      role: "Moderator",
      department: "Support",
    },
    {
      sno: 15,
      name: "Mia Young",
      email: "mia.young@example.com",
      role: "User",
      department: "Marketing",
    },
    {
      sno: 16,
      name: "Noah King",
      email: "noah.king@example.com",
      role: "Admin",
      department: "IT",
    },
    {
      sno: 17,
      name: "Olivia Scott",
      email: "olivia.scott@example.com",
      role: "Editor",
      department: "Content",
    },
    {
      sno: 18,
      name: "Paul Hall",
      email: "paul.hall@example.com",
      role: "User",
      department: "HR",
    },
    {
      sno: 19,
      name: "Quinn Allen",
      email: "quinn.allen@example.com",
      role: "Moderator",
      department: "Support",
    },
    {
      sno: 20,
      name: "Rachel Wright",
      email: "rachel.wright@example.com",
      role: "User",
      department: "Sales",
    },
    {
      sno: 21,
      name: "Sam Baker",
      email: "sam.baker@example.com",
      role: "Admin",
      department: "Finance",
    },
    {
      sno: 22,
      name: "Tina Gonzalez",
      email: "tina.gonzalez@example.com",
      role: "Editor",
      department: "Content",
    },
    {
      sno: 23,
      name: "Uma Carter",
      email: "uma.carter@example.com",
      role: "User",
      department: "HR",
    },
    {
      sno: 24,
      name: "Victor Evans",
      email: "victor.evans@example.com",
      role: "Moderator",
      department: "Support",
    },
    {
      sno: 25,
      name: "Will Perez",
      email: "will.perez@example.com",
      role: "User",
      department: "Sales",
    },
  ];
  
  export default users;
  